In [11]:
import numpy as np
from sklearn import preprocessing

data = np.array([[1,2],[3,4],[5,6]])
# data = np.array([[3,5],[7,4],[2,4]])
print("data : ",data)

# Mean Avreage
mean_val = data.mean(axis=0)
print("mean_val : ",mean_val)

# Standard Deviation
std = data.std(axis=0)
print("std : ",std)

# Mean Removal : it mean mean=0, std=1
final_val = data-mean_val
print("final_val : ",final_val)
print(final_val.mean(axis=0))
print(final_val.mean(axis=1))

# Scale()

final = preprocessing.scale(data)
print("final : ",final)
print(final.mean(axis=0))
print(final_val.std(axis=0))

data :  [[1 2]
 [3 4]
 [5 6]]
mean_val :  [3. 4.]
std :  [1.63299316 1.63299316]
final_val :  [[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
[0. 0.]
[-2.  0.  2.]
final :  [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
[0. 0.]
[1.63299316 1.63299316]


In [4]:
import pandas as pd
from sklearn import preprocessing

df = pd.read_csv("data.csv")
print(df)

data = df[['person','male','female']]
print(data.mean(axis=0))
print(data.std(axis=0))

mean_removed_data = preprocessing.scale(data)
print(mean_removed_data.mean(axis=0))
print(mean_removed_data.std(axis=0))

    year  person   male  female
0   2005   91.55  51.58   70.51
1   1993   33.27  64.53   38.07
2   2006   43.29  24.86   75.66
3   2013   72.82  90.72   42.20
4   2000   22.14  50.22   97.66
5   2005   65.24  83.59   47.42
6   1992   40.62  25.33   32.84
7   1993   90.74  38.69   89.02
8   1992   49.18  77.74   56.29
9   1993   96.80  42.65   72.85
10  2001   66.50  58.93   80.53
11  2005   79.84  88.38   17.70
12  1986   29.84  68.19   31.66
13  1994   95.32  96.26   48.06
14  1990    9.01  88.56   46.53
15  2011   13.10  82.27   79.22
16  2011   95.94  31.49   80.63
17  1993   68.61  65.56   90.67
18  2002   63.29  24.51   56.09
19  2011   46.02  85.18   43.39
20  2000   15.57  27.89   10.62
21  2004   79.50  59.22   99.42
22  2007   50.56  72.77   30.62
23  2005   46.38  15.34    6.57
24  1993   86.48  29.34   99.99
25  2007   64.87  55.95   91.14
26  1993   92.29  29.30   83.03
27  1999   55.89  11.75   41.72
28  2012   82.28  59.92   29.25
29  2000   40.49  59.06   58.62
30  2010

In [9]:
import numpy as np
import pandas as pd
# data = np.array([[1,2],[3,4],[5,6]])

data = pd.read_csv("data.csv")

# Define A Scaller Model for Scalling the data
scaller_model = preprocessing.MinMaxScaler()

# Apply data to the model : fit
op1 = scaller_model.fit(data)

#let the Model transfer the data according to Requirnment : transform
op2 = op1.transform(data)

#print Result
print(op2)

[[0.84       0.92893029 0.5255893  0.69903012]
 [0.6        0.31892401 0.66309195 0.36784074]
 [0.86       0.42380155 0.24187726 0.75160796]
 [1.         0.73288675 0.94117647 0.4100051 ]
 [0.74       0.2024283  0.51114886 0.97621235]
 [0.84       0.65354825 0.86547038 0.4632976 ]
 [0.58       0.39585514 0.2468677  0.31444615]
 [0.6        0.92045217 0.38872372 0.88800408]
 [0.58       0.48545112 0.80335528 0.55385401]
 [0.6        0.9838811  0.43077086 0.72291986]
 [0.76       0.66673645 0.60363134 0.80132721]
 [0.84       0.80636383 0.91633043 0.15987749]
 [0.46       0.28302282 0.70195371 0.30239918]
 [0.62       0.9683902  1.         0.46983155]
 [0.54       0.06499895 0.91824166 0.45421133]
 [0.96       0.10780825 0.85145466 0.78795304]
 [0.96       0.97487963 0.31227437 0.80234814]
 [0.6        0.68882144 0.67402846 0.90484941]
 [0.78       0.63313795 0.23816097 0.55181215]
 [0.96       0.45237597 0.88235294 0.42215416]
 [0.74       0.13366129 0.27404969 0.08759571]
 [0.82       

In [10]:
import numpy as np
# data = np.array([[1,2],[3,4],[5,6]])

data = pd.read_csv("data.csv")

#define a scaller model for scalling the data
scaller_model = preprocessing.MinMaxScaler()

#apply the data to model and let the model transfer the data accotdingly
op = scaller_model.fit_transform(data)
print(op)

[[0.84       0.92893029 0.5255893  0.69903012]
 [0.6        0.31892401 0.66309195 0.36784074]
 [0.86       0.42380155 0.24187726 0.75160796]
 [1.         0.73288675 0.94117647 0.4100051 ]
 [0.74       0.2024283  0.51114886 0.97621235]
 [0.84       0.65354825 0.86547038 0.4632976 ]
 [0.58       0.39585514 0.2468677  0.31444615]
 [0.6        0.92045217 0.38872372 0.88800408]
 [0.58       0.48545112 0.80335528 0.55385401]
 [0.6        0.9838811  0.43077086 0.72291986]
 [0.76       0.66673645 0.60363134 0.80132721]
 [0.84       0.80636383 0.91633043 0.15987749]
 [0.46       0.28302282 0.70195371 0.30239918]
 [0.62       0.9683902  1.         0.46983155]
 [0.54       0.06499895 0.91824166 0.45421133]
 [0.96       0.10780825 0.85145466 0.78795304]
 [0.96       0.97487963 0.31227437 0.80234814]
 [0.6        0.68882144 0.67402846 0.90484941]
 [0.78       0.63313795 0.23816097 0.55181215]
 [0.96       0.45237597 0.88235294 0.42215416]
 [0.74       0.13366129 0.27404969 0.08759571]
 [0.82       

In [13]:
import numpy as np
# data = np.array([[1,2],[3,4],[5,6]])
data = pd.read_csv("data.csv")

op = preprocessing.normalize(data,norm="l1")
print(op)

[[0.90370678 0.04126402 0.02324848 0.03178073]
 [0.93617741 0.01562801 0.03031186 0.01788273]
 [0.93310572 0.02013666 0.01156381 0.03519381]
 [0.90727169 0.03282043 0.04088807 0.0190198 ]
 [0.92165049 0.01020267 0.02314264 0.04500419]
 [0.91084611 0.02963771 0.03797388 0.02154231]
 [0.95274992 0.01942806 0.01211504 0.01570698]
 [0.90121866 0.0410319  0.01749531 0.04025413]
 [0.91577365 0.02260931 0.03573908 0.02587796]
 [0.90373192 0.04389425 0.01933977 0.03303405]
 [0.90667706 0.03013195 0.02670189 0.03648911]
 [0.91514067 0.03644131 0.04033922 0.0080788 ]
 [0.93870085 0.01410415 0.03223062 0.01496439]
 [0.89271324 0.04267474 0.04309557 0.02151645]
 [0.93247739 0.00422192 0.04149759 0.0218031 ]
 [0.92011768 0.0059938  0.03764201 0.03624651]
 [0.90623958 0.04323452 0.01419069 0.0363352 ]
 [0.89862208 0.0309355  0.02956029 0.04088212]
 [0.93294624 0.02949359 0.01142183 0.02613834]
 [0.92011768 0.0210561  0.03897346 0.01985276]
 [0.97367191 0.00758004 0.01357785 0.0051702 ]
 [0.89378897 

# Binarization

In [12]:
import numpy as np
from sklearn import preprocessing
data  = np.array([[3,5],[7,4],[2,4]])
binarized_data = preprocessing.Binarizer(threshold=5)
op = binarized_data.fit_transform(data)
print(data)
print(op)

[[3 5]
 [7 4]
 [2 4]]
[[0 0]
 [1 0]
 [0 0]]


# Label Encoding

In [18]:
data = ["apple","cherry","grapes", "mango","apple","cherry", "mango"]
labeled_data = preprocessing.LabelEncoder()
op = lebeled_data.fit_transform(data)
print(data)
print(op)

# testing the model
test_data = ['apple','cherry']
test_op = labeled_data.fit_transform(test_data)
print(test_op)

# inverse testing
test_data = [0,1]
test_op = labeled_data.inverse_transform(test_data)
print(test_op)

['apple', 'cherry', 'grapes', 'mango', 'apple', 'cherry', 'mango']
[0 1 2 3 0 1 3]
[0 1]
['apple' 'cherry']


In [ ]:
import numpy as np
# data = np.array([[1,2],[3,4],[5,6]])
data = pd.read_csv("data.csv")